version: '3.4'

services:
  course.api:
    image: contoso/course-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ContosoApp/src/Services/Course/Course.API/Dockerfile

    environment:
      - ConnectionString=Server=sqldata;Initial Catalog=CourseDb;User Id=sa;Password=Pass@word
    expose:
      - "80"
    ports:
      - "5101:80"
    #extra hosts can be used for standalone SQL Server or services at the dev PC
    extra_hosts:
      - "CESARDLSURFBOOK:10.0.75.1"
    depends_on:
      - sqldata

  student.api:
    image: contoso/student-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ContosoApp/src/Services/Student/Student.API/Dockerfile
    expose:
      - "81"
    ports:
      - "5102:81"

  enrollement.api:
    image: ${DOCKER_REGISTRY-}enrollement-api
    build:
      context: .
      dockerfile: ContosoApp/src/Services/Enrollement/Enrollement.API/Dockerfile
    depends_on:
      - course.api
      - student.api
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"