version: '3.4'

services:
  course.api:
    image: contoso/course-api:${TAG:-latest}
    depends_on:
     - "postgres_image"
    build:
      context: .
      dockerfile: ContosoApp/src/Services/Course/Course.API/Dockerfile
    ports:
      - "5101:80"
    environment:
      COURSE_DB_CONNECTION_STRING: "Server=postgres_image;port=5432; database=courseDb;username=postgres;password=Admin1*"

  student.api:
    image: contoso/student-api:${TAG:-latest}
    depends_on:
     - "postgres_image"
    build:
      context: .
      dockerfile: ContosoApp/src/Services/Student/Student.API/Dockerfile
    ports:
      - "5102:81"
    environment:
      STUDENT_DB_CONNECTION_STRING: "Server=postgres_image;port=5432; database=studentDb;username=postgres;password=Admin1*"

  enrollement.api:
    image: ${DOCKER_REGISTRY-}enrollement-api
    build:
      context: .
      dockerfile: ContosoApp/src/Services/Enrollement/Enrollement.API/Dockerfile
    depends_on:
      - course.api
      - student.api

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Admin1*"
      POSTGRES_DB: "courseDb"

  #pgadmin: 
  #  image: dpage/pgadmin4

volumes:
  db_volume:

#volumes:
#  postgres_data:
#  pgadmin_data:
